name: happyadmin
description: Happy Credit admin
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Icons
  cupertino_icons: ^1.0.0
  flutter_vector_icons: ^1.0.0
  flutter_remix: ^0.0.3

  # Firebase
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.2
  firebase_messaging: ^10.0.0
  cloud_firestore: ^2.2.0
  firebase_storage: ^8.0.5

  # User Interface
  lottie: ^1.0.1
  flutter_svg: ^0.21.0
  carousel_slider: ^3.0.0
  cached_network_image: ^3.0.0
  pin_code_fields: ^7.1.0
  otp_text_field: ^1.0.1
  auto_size_text: ^2.1.0
  jiffy: ^4.1.0
  image: ^3.0.2
  path: ^1.7.0
  path_provider: ^2.0.1
  uuid: ^3.0.4
  shimmer: ^2.0.0
  # lightbox: ^0.0.2
  google_fonts: ^2.0.0
  images_picker: ^1.2.4
  image_picker: ^0.7.5+3
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety
  secure_random: ^1.0.1
  crisp: ^0.1.4
  syncfusion_flutter_sliders: ^19.1.65-beta
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  flutter_hud: ^0.3.0
  flutter_onboard: ^1.0.0
  flutter_shimmer: ^2.0.0-prerelease-nullsafety
  dropdown_search: ^0.6.1
  awesome_card: ^1.1.5
  flutter_multi_formatter: ^2.2.0
  syncfusion_flutter_pdfviewer: ^19.1.67-beta
  flutter_web_data_table: ^1.0.0


  # State Management
  intl: ^0.17.0
  get: ^4.1.4
  get_storage: ^2.0.2

  # Functions
  http:
  location:
  url_launcher: ^6.0.3
  permission_handler: ^8.0.0+2

  # Payment
  razorpay_flutter: ^1.2.6
  eventify: ^1.0.0
  flutter_paystack: ^1.0.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4


# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  # adaptive_icon_background: "#000000"
  # adaptive_icon_foreground: "assets/icons/icon.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/logo.png
  fullscreen: false
  android: false
  ios: false
  web: true

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/